---
platform: linux

image_resource:
  type: docker-image
  source: { repository: concourse/bosh-cli }

inputs:
  - name: source-code

outputs:
  - name: new-repo

run:
  user: root
  path: sh
  args:
  - -exc
  - |
    git clone source-code new-repo
